# File paths
# TODO: #42 Add 'sections' paths to ensure consistency of filepath names throughout
- data:
    rawFilePath: data/raw/
    clnFilePath: data/processed/
    intFilePath: data/interim/

- viz:
    outPath: reports/figures/

- report-section:
    sentencing: sentencing/
    state-of-our-prisons: state-of-our-prisons/
    people-in-prison: people-in-prison/
    health-in-prison: health-in-prison/
    rehabilitation-and-resettlement: rehabilitation-and-resettlement/

# Configurations
- plotly:
    config:
        "scrollZoom": False
        "displayModeBar": False
        "editable": False
        "displaylogo": False
        "showAxisDragHandles": False
        "responsive": True