# File paths
# TODO: #42 Add 'sections' paths to ensure consistency of filepath names throughout
- data:
    rawFilePath: data/raw/
    clnFilePath: data/processed/
    intFilePath: data/interim/

- viz:
    outPath: reports/figures/

- report_section:
    sentences_explained: sentences_explained/
    sentencing: sentencing/
    state_of_our_prisons: state_of_our_prisons/
    people_in_prison: people_in_prison/
    health_in_prison: health_in_prison/
    rehabilitation_and_resettlement: rehabilitation_and_resettlement/

# Configurations
- plotly:
    config:
        "scrollZoom": False
        "displayModeBar": False
        "editable": False
        "displaylogo": False
        "showAxisDragHandles": False
        "responsive": True