# File paths
# TODO: #42 Add 'sections' paths to ensure consistency of filepath names throughout
- data:
    rawFilePath: data/raw/
    clnFilePath: data/processed/
    intFilePath: data/interim/

- viz:
    outPath: reports/figures/

- report_section:
    sentencing: sentencing/
    state_of_our_prisons: state-of-our-prisons/
    people_in_prison: people-in-prison/
    health_in_prison: health-in-prison/
    rehabilitation_and_resettlement: rehabilitation-and-resettlement/

# Configurations
- plotly:
    config:
        "scrollZoom": False
        "displayModeBar": False
        "editable": False
        "displaylogo": False
        "showAxisDragHandles": False
        "responsive": True