channels:
  - conda-forge
  - plotly
dependencies:
- pandas
- matplotlib
- seaborn
- plotly=6.0.0 # Rolled back to 6.0.0 due to issues with Chart Studio upload on 6.0.1
- python-kaleido
- plotly-geo
- chart-studio
- notebook
- jupyterlab
- ipywidgets
- python-dotenv
- black
- nbqa
- poppler
- lxml
- office365-rest-python-client
- nbautoexport
- xlrd
- mkdocs
- mkdocs-material