site_name: Prison Reform Trust—Bromley Briefings visualizations
site_description: A home for information on producing the visualization used in the Bromley Briefings Prison Factfile.
repo_url: https://github.com/Prison-Reform-Trust/bromley_briefings
edit_uri: edit/master/docs/docs
copyright: Written by <a href=https://prisonreformtrust.org.uk/>Prison Reform Trust</a>
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: prison-reform-trust
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  icon:
    admonition:
      tip: material/tooltip-check-outline
extra_css:
  - css/extra.css
nav:
  - Welcome: index.md
  - Data catalogue: data-catalogue.md
